/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SelectTeamRouteImport } from './routes/select-team'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAhorrosRouteImport } from './routes/_app.ahorros'
import { Route as AppAjustesRouteImport } from './routes/_app.ajustes'
import { Route as AppBackupRouteImport } from './routes/_app.backup'
import { Route as AppBuscarRouteImport } from './routes/_app.buscar'
import { Route as AppComparativaRouteImport } from './routes/_app.comparativa'
import { Route as AppEquiposRouteImport } from './routes/_app.equipos'
import { Route as AppEvolucionRouteImport } from './routes/_app.evolucion'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppHistorialRouteImport } from './routes/_app.historial'
import { Route as AppPrestamosRouteImport } from './routes/_app.prestamos'
import { Route as AppPresupuestosRouteImport } from './routes/_app.presupuestos'
import { Route as AppProximosRouteImport } from './routes/_app.proximos'
import { Route as AppTransferirRouteImport } from './routes/_app.transferir'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTeamRoute = SelectTeamRouteImport.update({
  id: '/select-team',
  path: '/select-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAhorrosRoute = AppAhorrosRouteImport.update({
  id: '/ahorros',
  path: '/ahorros',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppComparativaRoute = AppComparativaRouteImport.update({
  id: '/comparativa',
  path: '/comparativa',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposRoute = AppEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolucionRoute = AppEvolucionRouteImport.update({
  id: '/evolucion',
  path: '/evolucion',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppPrestamosRoute = AppPrestamosRouteImport.update({
  id: '/prestamos',
  path: '/prestamos',
  getParentRoute: () => AppRoute,
} as any)
const AppPresupuestosRoute = AppPresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppProximosRoute = AppProximosRouteImport.update({
  id: '/proximos',
  path: '/proximos',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferirRoute = AppTransferirRouteImport.update({
  id: '/transferir',
  path: '/transferir',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-team': typeof SelectTeamRoute
  '/ahorros': typeof AppAhorrosRoute
  '/ajustes': typeof AppAjustesRoute
  '/backup': typeof AppBackupRoute
  '/buscar': typeof AppBuscarRoute
  '/comparativa': typeof AppComparativaRoute
  '/equipos': typeof AppEquiposRoute
  '/evolucion': typeof AppEvolucionRoute
  '/favorites': typeof AppFavoritesRoute
  '/historial': typeof AppHistorialRoute
  '/prestamos': typeof AppPrestamosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/proximos': typeof AppProximosRoute
  '/transferir': typeof AppTransferirRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-team': typeof SelectTeamRoute
  '/ahorros': typeof AppAhorrosRoute
  '/ajustes': typeof AppAjustesRoute
  '/backup': typeof AppBackupRoute
  '/buscar': typeof AppBuscarRoute
  '/comparativa': typeof AppComparativaRoute
  '/equipos': typeof AppEquiposRoute
  '/evolucion': typeof AppEvolucionRoute
  '/favorites': typeof AppFavoritesRoute
  '/historial': typeof AppHistorialRoute
  '/prestamos': typeof AppPrestamosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/proximos': typeof AppProximosRoute
  '/transferir': typeof AppTransferirRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-team': typeof SelectTeamRoute
  '/_app/ahorros': typeof AppAhorrosRoute
  '/_app/ajustes': typeof AppAjustesRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/comparativa': typeof AppComparativaRoute
  '/_app/equipos': typeof AppEquiposRoute
  '/_app/evolucion': typeof AppEvolucionRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/prestamos': typeof AppPrestamosRoute
  '/_app/presupuestos': typeof AppPresupuestosRoute
  '/_app/proximos': typeof AppProximosRoute
  '/_app/transferir': typeof AppTransferirRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/select-team'
    | '/ahorros'
    | '/ajustes'
    | '/backup'
    | '/buscar'
    | '/comparativa'
    | '/equipos'
    | '/evolucion'
    | '/favorites'
    | '/historial'
    | '/prestamos'
    | '/presupuestos'
    | '/proximos'
    | '/transferir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/select-team'
    | '/ahorros'
    | '/ajustes'
    | '/backup'
    | '/buscar'
    | '/comparativa'
    | '/equipos'
    | '/evolucion'
    | '/favorites'
    | '/historial'
    | '/prestamos'
    | '/presupuestos'
    | '/proximos'
    | '/transferir'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/select-team'
    | '/_app/ahorros'
    | '/_app/ajustes'
    | '/_app/backup'
    | '/_app/buscar'
    | '/_app/comparativa'
    | '/_app/equipos'
    | '/_app/evolucion'
    | '/_app/favorites'
    | '/_app/historial'
    | '/_app/prestamos'
    | '/_app/presupuestos'
    | '/_app/proximos'
    | '/_app/transferir'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SelectTeamRoute: typeof SelectTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-team': {
      id: '/select-team'
      path: '/select-team'
      fullPath: '/select-team'
      preLoaderRoute: typeof SelectTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ahorros': {
      id: '/_app/ahorros'
      path: '/ahorros'
      fullPath: '/ahorros'
      preLoaderRoute: typeof AppAhorrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparativa': {
      id: '/_app/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof AppComparativaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos': {
      id: '/_app/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof AppEquiposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evolucion': {
      id: '/_app/evolucion'
      path: '/evolucion'
      fullPath: '/evolucion'
      preLoaderRoute: typeof AppEvolucionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prestamos': {
      id: '/_app/prestamos'
      path: '/prestamos'
      fullPath: '/prestamos'
      preLoaderRoute: typeof AppPrestamosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presupuestos': {
      id: '/_app/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof AppPresupuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proximos': {
      id: '/_app/proximos'
      path: '/proximos'
      fullPath: '/proximos'
      preLoaderRoute: typeof AppProximosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transferir': {
      id: '/_app/transferir'
      path: '/transferir'
      fullPath: '/transferir'
      preLoaderRoute: typeof AppTransferirRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAhorrosRoute: typeof AppAhorrosRoute
  AppAjustesRoute: typeof AppAjustesRoute
  AppBackupRoute: typeof AppBackupRoute
  AppBuscarRoute: typeof AppBuscarRoute
  AppComparativaRoute: typeof AppComparativaRoute
  AppEquiposRoute: typeof AppEquiposRoute
  AppEvolucionRoute: typeof AppEvolucionRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppPrestamosRoute: typeof AppPrestamosRoute
  AppPresupuestosRoute: typeof AppPresupuestosRoute
  AppProximosRoute: typeof AppProximosRoute
  AppTransferirRoute: typeof AppTransferirRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAhorrosRoute: AppAhorrosRoute,
  AppAjustesRoute: AppAjustesRoute,
  AppBackupRoute: AppBackupRoute,
  AppBuscarRoute: AppBuscarRoute,
  AppComparativaRoute: AppComparativaRoute,
  AppEquiposRoute: AppEquiposRoute,
  AppEvolucionRoute: AppEvolucionRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppPrestamosRoute: AppPrestamosRoute,
  AppPresupuestosRoute: AppPresupuestosRoute,
  AppProximosRoute: AppProximosRoute,
  AppTransferirRoute: AppTransferirRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SelectTeamRoute: SelectTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
